<?php
$z[0]=Array("id","",51,62);
$z[0][4]=array();
$z[1]=Array("title","",71,85);
$z[1][4]=array();
$z[2]=Array("title","",107,121);
$z[2][4]=array();
$z[3]=Array("typename","",182,199);
$z[3][4]=array();
$z[4]=Array("litpic","",243,258);
$z[4][4]=array();
$z[5]=Array("title","",266,280);
$z[5][4]=array();
$z[6]=Array("description","",310,360);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,100)";

?>