<dl class="cl">
        <dd class="m"> <a href="[field:arcurl/]"> <img width="300" height="94" src="images/1-1PP21P522c2.jpg" class="attachment-post-thumbnail wp-post-image" alt="3523" /> </a> </dd>
        <dt> <a href="[field:typeurl/]" class="cat">[field:typename/]<i></i></a> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></dt>
        <p> <em>[field:pubdate function='strftime("%Y-%m-%d",@me)'/] </em> <em>查看(<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script>)</em> </p>
        <dd> [field:description function='cn_substr(@me,250)'/]...</dd>
      </dl>