<div class='data'>
      <div class="m"> <a href="[field:arcurl/]" class="imgurl"> <img width="300" height="200" src="[field:litpic/]" class="attachment-post-thumbnail wp-post-image" alt="[field:title/]"/> </a> </div>
      <div class="info">
        <h2><em class="view"><script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script></em><a href="[field:arcurl/]" rel="bookmark">[field:title/]</a></h2>
      </div>
    </div>