<div class="case-list-data"> <a href="view.php?aid=[field:id/]" title="[field:title/]" class="s">
    <h6>[field:title/]</h6>
    <p class="class cl"> <span class="z">所属行业:[field:typename/]</span> </p>
    <div class="m"> <img src="[field:litpic/]"  alt="[field:title/]"> </div>
    <p class="des">...</p>
    <p class="all cl"> <span class="z">了解更多</span> <span class="y"><i class="iconfont">&#xe6a7;</i></span> </p>
    </a> </div>