<?php
$z[0]=Array("type","<a href=\"list.php?tid=[field:id/]\"> <i class=\"iconfont\">&#xe696;</i> <span>服务</span> </a> ",104,233);
$z[0][4]=array();
$z[0][4]['typeid']="12";
$z[1]=Array("type","<a href=\"list.php?tid=[field:id/]\"> <i class=\"iconfont\">&#xe71b;</i> <span>案例</span> </a> ",235,363);
$z[1][4]=array();
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"list.php?tid=[field:id/]\"> <i class=\"iconfont\">&#xe6bf;</i> <span>新闻</span> </a> ",365,493);
$z[2][4]=array();
$z[2][4]['typeid']="4";
$z[3]=Array("type","<a href=\"list.php?tid=[field:id/]\"> <i class=\"iconfont\">&#xe6c7;</i> <span>知识</span> </a>",495,623);
$z[3][4]=array();
$z[3][4]['typeid']="13";
$z[4]=Array("global","",669,690);
$z[4][4]=array();
$z[4][4]['name']="cfg_dh";

?>