<?php
$z[0]=Array("global","",142,168);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",241,262);
$z[1][4]=array();
$z[1][4]['name']="cfg_dh";
$z[2]=Array("channelartlist","\r\n          <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n            <ul class=\"sub-menu\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",402,795);
$z[2][4]=array();
$z[2][4]['row']="10";
$z[2][4]['typeid']="top";

?>