<?php
$z[0]=Array("field","",64,83);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",151,180);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",220,278);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("channel","\r\n      <li class=\"cat-item\"><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n      ",1473,1638);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[5]=Array("list","\r\n  <div class=\"post-list-data\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\" class=\"s cl\">\r\n    <div class=\"m z\"> <img src=\"[field:litpic/]\"  alt=\"[field:title/]\"> </div>\r\n    <h6>[field:title/]</h6>\r\n    <p class=\"cl\"> <span class=\"z\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span><span class=\"y\"><i class=\"iconfont\">&#xe6e6;</i><script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></span> </p>\r\n    </a> </div>\r\n  ",1936,2503);
$z[5][4]=array();
$z[5][4]['pagesize']="8";
$z[5][4]['titlelen']="60";
$z[6]=Array("pagelist","",2572,2629);
$z[6][4]=array();
$z[6][4]['listitem']="index,end,pageno";
$z[6][4]['listsize']="3";
$z[7]=Array("include","",2654,2691);
$z[7][4]=array();
$z[7][4]['filename']="foot_m.htm";

?>