<?php
$z[0]=Array("likeart","<a href=\"[field:arcurl/]\">\r\n      <h2 class=\"cl\"><span>[field:typename/]</span></h2>\r\n      <h3>[field:title /]</h3>\r\n      <p>[field:description function='cn_substr(@me,250)'/]...</p>\r\n      </a> ",49,297);
$z[0][4]=array();
$z[0][4]['row']="1";
$z[0][4]['titlelen']="60";
$z[1]=Array("type","<a class=\"btn\" href=\"[field:typelink /]\">查看详情</a>",610,702);
$z[1][4]=array();
$z[1][4]['typeid']="12";
$z[2]=Array("type","<a class=\"btn\" href=\"[field:typelink /]\">查看详情</a>",927,1019);
$z[2][4]=array();
$z[2][4]['typeid']="12";
$z[3]=Array("type","<a class=\"btn\" href=\"[field:typelink /]\">查看详情</a>",1270,1362);
$z[3][4]=array();
$z[3][4]['typeid']="12";
$z[4]=Array("type","<a class=\"btn\" href=\"[field:typelink /]\">查看详情</a>",1596,1688);
$z[4][4]=array();
$z[4][4]['typeid']="12";
$z[5]=Array("type","<a class=\"btn\" href=\"[field:typelink /]\">获取更多</a>",1941,2033);
$z[5][4]=array();
$z[5][4]['typeid']="12";
$z[6]=Array("global","",2190,2211);
$z[6][4]=array();
$z[6][4]['name']="cfg_dh";
$z[7]=Array("global","",2263,2284);
$z[7][4]=array();
$z[7][4]['name']="cfg_sj";
$z[8]=Array("global","",2349,2370);
$z[8][4]=array();
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",2473,2494);
$z[9][4]=array();
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",2597,2618);
$z[10][4]=array();
$z[10][4]['name']="cfg_qq";

?>